### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by magmumparis** [jshemas/openGraphScraper#32]
.../node_modules/domutils/lib/querying.js:83
function findAll(test, elems){
                ^

RangeError: Maximum call stack size exceeded

occurs when calling ogs on a url that contains large image, e.g.

https://upload.wikimedia.org/wikipedia/commons/a/a2/Overlook_Hong_Kong_Island_north_coast,_Victoria_Harbour_and_Kowloon_from_middle_section_of_Lugard_Road_at_daytime_(enlarged_version_and_better_contrast,_revised).jpg

**Comment by jshemas** [comment]
Neat bug! Thank you for the example URL. I'm not sure what is the best way of fixing this since `request` dose not have a "max page size" option build in.

I did however find this SO post: http://stackoverflow.com/questions/25080121/node-js-and-request-limiting-the-file-size-of-downloaded-file

I'll look into this more, but if you want to make a PR in the mean time, that would be awesome.

**Comment by tmaslen** [comment]
I've had this issue before with open-graph-scraper. I think its to do with the fact that its trying to convert a binary file into a DOM via cheerio.

I get round this by screen the file types of what I pass to open-graph-scraper.

**Comment by jshemas** [comment]
This has been fixed in version `2.4.2` - We now make sure it's a html page before trying to get open graph info from it.
