### ISSUE TITLE
Getting are you a robot in response

### ISSUE THREAD

**Issue by AnishaChhatwani** [jshemas/openGraphScraper#93]
I am trying to fetch the metadata of this url:
https://www.bloomberg.com/news/articles/2020-06-24/pentagon-names-20-chinese-firms-it-says-are-military-controlled?cmpid=socialflow-twitter-business&utm_medium=social&utm_content=business&utm_source=twitter&utm_campaign=socialflow-organic

I get this in response:
{ ogTitle: 'Bloomberg - Are you a robot?', ogImage: [] }

I get the correct data when I run it locally. But when I try to fetch the meta data on my production, it gives the above response

**Comment by jshemas** [comment]
Hello,

I have run into this issue a few times and this basically the same issue as https://github.com/jshemas/openGraphScraper/issues/49. In short, you are going to need to use a proxy because the website is blocking you from scripting it. Right now OGS does not support Proxies, but i'm hoping to build that support in the near future.

**Comment by jshemas** [comment]
In the mean time, you could do the http request in your own app server with a proxy and just pass the HTML results into ogs.

**Comment by jshemas** [comment]
OGS now supports proxies! Example of how to use proxies: https://github.com/jshemas/openGraphScraper#proxy-example

You can also try setting the `user-agent` header.
